import { Camera, MapPin, Cpu, FileImage, type LucideIcon } from 'lucide-react';

interface SoftwareTrace {
  field: string;
  value: string;
  aiRelated: boolean;
}

interface GPSData {
  lat: number;
  lng: number;
}

interface Dimensions {
  width: number;
  height: number;
}

interface ExifData {
  Model?: string;
  Make?: string;
  LensModel?: string;
  FocalLength?: number;
  FNumber?: number;
  ISO?: number;
  ExposureTime?: number;
  DateTimeOriginal?: string;
}

interface MetadataPanelData {
  exif?: ExifData | null;
  hash?: string;
  gps?: GPSData | null;
  dimensions?: Dimensions | null;
  softwareTraces?: SoftwareTrace[];
}

export default function MetadataPanel({ data }: { data: MetadataPanelData }) {
  if (!data?.exif && !data?.hash) {
    return (
      <div className="p-4 border border-[#F27D26]/20 rounded-xl bg-[#0A0A0A]">
        <div className="flex items-center gap-2 text-[10px] font-mono text-[#F27D26] uppercase tracking-widest mb-2">
          <Camera className="w-4 h-4" />
          Metadata Analysis
        </div>
        <p className="text-xs opacity-60">
          No metadata found. This could indicate:
        </p>
        <ul className="text-[10px] opacity-40 mt-2 space-y-1 list-disc list-inside">
          <li>Image was generated by AI (AI tools often strip/omit EXIF)</li>
          <li>Metadata was intentionally removed</li>
          <li>Image format doesn't support EXIF</li>
        </ul>
        {data?.hash && (
          <p className="text-[10px] font-mono mt-2 opacity-30">
            SHA-256: {data.hash.substring(0, 16)}...
          </p>
        )}
      </div>
    );
  }

  const sections: Array<{ title: string; icon: LucideIcon; items: Array<{ label: string; value: string }> }> = [];

  if (data.exif) {
    sections.push({
      title: 'Camera',
      icon: Camera,
      items: [
        { label: 'Camera', value: data.exif.Model || data.exif.Make || 'Unknown' },
        { label: 'Lens', value: data.exif.LensModel || 'Unknown' },
        { label: 'Focal Length', value: data.exif.FocalLength ? `${data.exif.FocalLength}mm` : 'Unknown' },
        { label: 'Aperture', value: data.exif.FNumber ? `f/${data.exif.FNumber}` : 'Unknown' },
        { label: 'ISO', value: data.exif.ISO != null ? String(data.exif.ISO) : 'Unknown' },
        { label: 'Shutter', value: data.exif.ExposureTime ? `${data.exif.ExposureTime}s` : 'Unknown' },
        { label: 'Date Taken', value: data.exif.DateTimeOriginal ? new Date(data.exif.DateTimeOriginal).toLocaleString() : 'Unknown' },
      ]
    });
  }

  if (data.gps) {
    sections.push({
      title: 'GPS Location',
      icon: MapPin,
      items: [
        { label: 'Latitude', value: data.gps.lat.toFixed(6) },
        { label: 'Longitude', value: data.gps.lng.toFixed(6) },
      ]
    });
  }

  if (data.dimensions) {
    sections.push({
      title: 'File',
      icon: FileImage,
      items: [
        { label: 'Dimensions', value: `${data.dimensions.width}\u00D7${data.dimensions.height}` },
        { label: 'SHA-256', value: data.hash?.substring(0, 16) + '...' },
      ]
    });
  }

  if (data.softwareTraces?.length) {
    sections.push({
      title: 'Software Traces',
      icon: Cpu,
      items: data.softwareTraces.map((t: any) => ({
        label: t.field,
        value: t.value + (t.aiRelated ? ' \u26A0\uFE0F' : ''),
      }))
    });
  }

  return (
    <div className="space-y-3">
      {sections.map((section, i) => (
        <div key={i} className="p-4 border border-[#141414] rounded-xl bg-[#0A0A0A]">
          <div className="flex items-center gap-2 text-[10px] font-mono text-[#F27D26] uppercase tracking-widest mb-3">
            <section.icon className="w-4 h-4" />
            {section.title}
          </div>
          <div className="grid grid-cols-2 gap-x-4 gap-y-2">
            {section.items.map((item, j) => (
              <div key={j}>
                <p className="text-[9px] opacity-40 uppercase">{item.label}</p>
                <p className="text-xs font-mono">{item.value}</p>
              </div>
            ))}
          </div>
        </div>
      ))}
    </div>
  );
}
